<?php
/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function post_range_help($path, $arg) {
  switch ($path) {
    case "admin/help#post_range":
      return '<p>' . t("Allows you to hide parts of posts.") . '</p>';
  }
}
/**
 * Implements hook_block_info().
 */
function post_range_block_info() {
  $blocks['post_range'] = array(
    // The name that will appear in the block list.
    'info' => ('Post Range'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}
